name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zenity libwayland-dev wayland-protocols libxkbcommon-dev
    
    - name: Build engine and sample bot
      run: make
    
    - name: Build tournament
      run: make tournament
    
    - name: Test engine
      run: ./engine ./sample_bot ./sample_bot ./sample_bot ./sample_bot ./sample_bot
    
    - name: Build viewer
      run: |
        cd viewer
        cmake -B build
        cmake --build build
